---
title: "Comparison of Fixed Weights"
author: "Matt Secrest and Isaac Gravestock"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{8. Comparison of Fixed Weights}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

Comparison of methods for fixed weights. Using weighted regression in a standard `glm` and
a weighted likelihood in Stan with `psborrow2` compared with the methods in `BayesPPD`.


# Logistic regression

```{r}
head(as.data.frame(example_matrix))
```


```{r}
logistic_glm_reslist <- lapply(c(0, 0.25, 0.5, 0.75, 1), function(w) {
  exp_glm <- glm(
    resp ~ trt + cov1 + cov2,
    data = as.data.frame(example_matrix),
    family = binomial,
    weights = ifelse(sim_data_exp$ext == 1, w, 1)
  )
  glm_summary <- summary(exp_glm)$coef
  ci <- confint(exp_glm)
  data.frame(
    fitter = "glm",
    borrowing = w,
    variable = c("(Intercept)", "trt", "cov1", "cov2"),
    estimate = glm_summary[, "Estimate"],
    lower = ci[, 1],
    upper = ci[, 2]
  )
})
```

```{r}
# Set parameters of the slice sampler
lower_limits <- rep(-100, 5) # The dimension is the number of columns of x plus 1 (intercept)
upper_limits <- rep(100, 5)
slice_widths <- rep(1, 5)

n_mc <- 10000 # nMC should be larger in practice
n_bi <- 1000

logistic_ppd_reslist <- lapply(c(0, 0.25, 0.5, 0.75, 1), function(w) {
  exp_ppd <- glm.fixed.a0(
    data.type = "Bernoulli",
    data.link = "Logistic",
    y = example_matrix[example_matrix[, "ext"] == 0, ][, "resp"],
    x = example_matrix[example_matrix[, "ext"] == 0, ][, c("trt", "cov1", "cov2")],
    historical = list(list(
      y0 = example_matrix[example_matrix[, "ext"] == 1, ][, "resp"],
      x0 = example_matrix[example_matrix[, "ext"] == 1, ][, c("cov1", "cov2")],
      a0 = w
    )),
    lower.limits = lower_limits,
    upper.limits = upper_limits,
    slice.widths = slice_widths,
    nMC = n_mc,
    nBI = n_bi
  )
  ci <- apply(exp_ppd, 2, quantile, probs = c(0.025, 0.975))
  data.frame(
    fitter = "BayesPPD",
    borrowing = w,
    variable = c("(Intercept)", "trt", "cov1", "cov2"),
    estimate = colMeans(exp_ppd),
    lower = ci[1, ],
    upper = ci[2, ]
  )
})
```


```{r}
logistic_psb_reslist <- lapply(c(0, 0.25, 0.5, 0.75, 1), function(w) {
  exp_test <- create_analysis_obj(
    data_matrix = as.matrix(cbind(example_matrix, w = ifelse(example_matrix[, "ext"] == 1, w, 1))),
    covariates = add_covariates(c("cov1", "cov2"),
      priors = normal_prior(0, 100)
    ),
    borrowing = borrowing_details("Full borrowing",
      ext_flag_col = "ext",
    ),
    treatment = treatment_details("trt", normal_prior(0, 100)),
    outcome = logistic_bin_outcome("resp",
      baseline_prior = normal_prior(0, 1000),
      weight_var = "w"
    )
  )

  mcmc_exp_test <- mcmc_sample(exp_test)
  mcmc_summary <- mcmc_exp_test$summary(
    variables = c("alpha", "beta_trt", "beta[1]", "beta[2]"),
    mean,
    ~ quantile(.x, probs = c(0.025, 0.975))
  )

  data.frame(
    fitter = "psborrow2",
    borrowing = w,
    variable = c("(Intercept)", "trt", "cov1", "cov2"),
    estimate = mcmc_summary$mean,
    lower = mcmc_summary$`2.5%`,
    upper = mcmc_summary$`97.5%`
  )
})
```

```{r}
logistic_res_df <- do.call(rbind, c(logistic_glm_reslist, logistic_ppd_reslist, logistic_psb_reslist))
logistic_res_df$borrowing <- logistic_res_df$borrowing + (as.numeric(factor(logistic_res_df$fitter)) - 2) / 100
ggplot(logistic_res_df, aes(x = borrowing, y = estimate, group = fitter, colour = fitter)) +
  # geom_errorbar(aes(ymin = lower, ymax = upper)) +
  geom_point() +
  facet_wrap(~variable, scales = "free")
```

# Exponentially distributed outcomes

```{r}
sim_data_exp <- cbind(
  simsurv::simsurv(
    dist = "exponential",
    x = as.data.frame(example_matrix[, c("trt", "cov1", "cov2", "ext")]),
    betas = c("trt" = 1.3, "cov1" = 1, "cov2" = 0.1, "ext" = -0.4),
    lambdas = 5
  ),
  example_matrix[, c("trt", "cov1", "cov2", "ext")],
  censor = 0
)
```

```{r}
# Set parameters of the slice sampler
lower_limits <- rep(-100, 5) # The dimension is the number of columns of x plus 1 (intercept)
upper_limits <- rep(100, 5)
slice_widths <- rep(1, 5)

n_mc <- 10000
n_bi <- 1000

ppd_reslist <- lapply(c(0, 0.25, 0.5, 0.75, 1), function(w) {
  exp_ppd <- glm.fixed.a0(
    data.type = "Exponential",
    data.link = "Log",
    y = sim_data_exp[sim_data_exp$ext == 0, ]$eventtime,
    x = as.matrix(sim_data_exp[sim_data_exp$ext == 0, c("trt", "cov1", "cov2")]),
    historical = list(list(
      y0 = sim_data_exp[sim_data_exp$ext == 1, ]$eventtime,
      x0 = as.matrix(sim_data_exp[sim_data_exp$ext == 1, c("cov1", "cov2")]),
      a0 = w
    )),
    lower.limits = lower_limits,
    upper.limits = upper_limits,
    slice.widths = slice_widths,
    nMC = n_mc,
    nBI = n_bi
  )
  data.frame(
    fitter = "BayesPPD",
    borrowing = w,
    variable = c("(Intercept)", "trt", "cov1", "cov2"),
    estimate = colMeans(exp_ppd)
  )
})
```


```{r}
glm_reslist <- lapply(c(0, 0.25, 0.5, 0.75, 1), function(w) {
  exp_glm <- glm(
    eventtime ~ trt + cov1 + cov2,
    data = sim_data_exp,
    family = Gamma(link = "log"),
    weights = ifelse(sim_data_exp$ext == 1, w, 1)
  )
  est <- summary(exp_glm, dispersion = 1)$coef[, "Estimate"]
  data.frame(
    fitter = "glm",
    borrowing = w,
    variable = c("(Intercept)", "trt", "cov1", "cov2"),
    estimate = -est
  )
})
```

```{r}
psb_reslist <- lapply(c(0, 0.25, 0.5, 0.75, 1), function(w) {
  exp_test <- create_analysis_obj(
    data_matrix = as.matrix(cbind(sim_data_exp, w = ifelse(example_matrix[, "ext"] == 1, w, 1))),
    covariates = add_covariates(c("cov1", "cov2"),
      priors = normal_prior(0, 100)
    ),
    borrowing = borrowing_details("Full borrowing",
      ext_flag_col = "ext",
    ),
    treatment = treatment_details("trt", normal_prior(0, 100)),
    outcome = exp_surv_dist("eventtime", "censor",
      baseline_prior = normal_prior(0, 1000),
      weight_var = "w"
    )
  )

  mcmc_exp_test <- mcmc_sample(exp_test)
  # mcmc_exp_test
  data.frame(
    fitter = "psborrow2",
    borrowing = w,
    variable = c("(Intercept)", "trt", "cov1", "cov2"),
    estimate = mcmc_exp_test$summary(variables = c("alpha", "beta_trt", "beta[1]", "beta[2]"))$mean
  )
})
```

```{r}
res_df <- do.call(rbind, c(glm_reslist, ppd_reslist, psb_reslist))
res_df$fitter[41:60] <- "psborrow2"
ggplot(res_df, aes(x = borrowing, y = estimate, group = fitter, colour = fitter)) +
  geom_point() +
  facet_wrap(~variable, scales = "free")
```
