# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, test-new-gha]
  pull_request:
    branches: [main, master, test-new-gha]

name: R-CMD-check

jobs:
  R-CMD-check:
    steps:
      - run: echo "Running on ${{ matrix.config.os }}"